$WALLPAPER_PATH=$HOME/Pictures/wallpapers/VRChat_2024-12-06_21-26-45.459_3840x2160.png
$ASCII_WALLPAPER_PATH=$HOME/Pictures/wallpapers/ascii_wallpaper.png

wallpaper {
 path = $ASCII_WALLPAPER_PATH
}
