#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = LIBVA_DRIVER_NAME,radeonsi
env = __GLX_VENDOR_LIBRARY_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi

# set dark theme for gtk apps
env = GTK_THEME,Adwaita:dark
# also this for some reason so the theme set by gsettings gets picked up https://wiki.archlinux.org/title/GTK#GTK_3_and_GTK_4
env = ADW_DISABLE_PORTAL=1
