##############################
########### WINDOWS ##########
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name=base
    suppress_event=maximize
    idle_inhibit=fulscreen
}

# default workspaces for applications
windowrule {
    name=default-workspace-1-dc
    match:class=^([Vv]esktop)$
    workspace=1
}

windowrule {
    name=default-workspace-2-dc-popout
    match:class=^([Vv]esktop)$
    match:initial_title=^([Dd]iscord [Pp]opout)$
    workspace=2
}

# opacity
windowrule = opacity 0.9 0.85, match:class ^([Ff]irefox)$
windowrule = opacity 1 1,match:title (.*)(- YouTube )(.*)
windowrule = opacity 0.9 0.7, match:class ^(com.mitchellh.ghostty)$
windowrule = opacity 1 1, match:class ^(jetbrains-.+)$
windowrule = opacity 0.9 0.85, match:class ^([Dd]iscord|[Vv]esktop)$

# IntelliJ
## search
windowrule = size 80% 80%, match:class ^(jetbrains-idea)$, match:title  ^( )$
windowrule = center on, match:class ^(jetbrains-idea)$, match:title  ^( )$
windowrule = monitor DP-1, match:class ^(jetbrains-idea)$, match:title  ^( )$
## commit push
windowrule = float on, match:class ^(jetbrains-idea)$, match:title  ^(Push Commits)$
windowrule = size 80% 80%, match:class ^(jetbrains-idea)$, match:title  ^(Push Commits)$
windowrule = center on, match:class ^(jetbrains-idea)$, match:title  ^(Push Commits)$
windowrule = monitor DP-1, match:class ^(jetbrains-idea)$, match:title  ^(Push Commits)$

# Discord
## popout
windowrule = opacity 1 1.5, match:class ^([Vv]esktop)$, match:initial_title ^([Dd]iscord [Pp]opout)$

# Bolt (osrs launcher)
windowrule = float on, match:class ^(bolt-launcher)$

# godot engine
windowrule = tile on, match:initial_title ^(Godot)$

##############################
######### WORKSPACES #########
##############################

$main = DP-1
$top = DP-2
$side = HDMI-A-1

workspace = 1, monitor:$side
workspace = 2, monitor:$top
workspace = 3, monitor:$top
workspace = 4, monitor:$top
workspace = 5, monitor:$main
workspace = 6, monitor:$main
workspace = 7, monitor:$main
workspace = 8, monitor:$main
workspace = 9, monitor:$main
workspace = 10, monitor:$main

