##############################
########### WINDOWS ##########
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# windowrule v2 to avoid idle for fullscreen apps
windowrulev2 = idleinhibit fullscreen, class:^.*$
windowrulev2 = idleinhibit fullscreen, title:^.*$
windowrulev2 = idleinhibit fullscreen, fullscreen:1

# windowrule v2 move to workspace
# windowrulev2 = workspace 1, class:^([Ll]utris)$
windowrulev2 = workspace 1, class:^([Vv]esktop)$
windowrulev2 = workspace 2, class:^([Vv]esktop)$, initialTitle:^([Dd]iscord [Pp]opout)$
windowrulev2 = workspace 2, class:^([Tt]eams)$

# opacity
windowrulev2 = opacity 0.9 0.85, class:^([Ff]irefox)$
windowrulev2 = opacity 1 1,title:(.*)(- YouTube )(.*)
windowrulev2 = opacity 0.9 0.7, class:^(com.mitchellh.ghostty)$
windowrulev2 = opacity 1 1, class:^(jetbrains-.+)$
windowrulev2 = opacity 0.9 0.85, class:^([Dd]iscord|[Vv]esktop)$

# IntelliJ
## search
windowrulev2 = size 80% 80%, class:^(jetbrains-idea)$, title: ^( )$
windowrulev2 = center, class:^(jetbrains-idea)$, title: ^( )$
windowrulev2 = monitor DP-1, class:^(jetbrains-idea)$, title: ^( )$
## commit push
windowrulev2 = float, class:^(jetbrains-idea)$, title: ^(Push Commits)$
windowrulev2 = size 80% 80%, class:^(jetbrains-idea)$, title: ^(Push Commits)$
windowrulev2 = center, class:^(jetbrains-idea)$, title: ^(Push Commits)$
windowrulev2 = monitor DP-1, class:^(jetbrains-idea)$, title: ^(Push Commits)$

# Discord
## popout
windowrulev2 = opacity 1 1.5, class:^([Vv]esktop)$, initialTitle:^([Dd]iscord [Pp]opout)$

 
##############################
######### WORKSPACES #########
##############################

$main = DP-2
$top = DP-3
$side = HDMI-A-1

workspace = 1, monitor:$side
workspace = 2, monitor:$top
workspace = 3, monitor:$top
workspace = 4, monitor:$top
workspace = 5, monitor:$main
workspace = 6, monitor:$main
workspace = 7, monitor:$main
workspace = 8, monitor:$main
workspace = 9, monitor:$main
workspace = 10, monitor:$main

